name: Android Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2

      - name: Install dependencies
        run: flutter pub get

      - name: Run Linting tests
        run: flutter analyze

      - name: Run Unit Tests
        run: flutter test

      - name: Build APK
        run: flutter build apk --release

      - name: Deploy to Appetize.io
        run: |
          APPETIZE_API_TOKEN=${{ secrets.APPETIZE_API_TOKEN }}
          APK_PATH=build/app/outputs/flutter-apk/app-release.apk
          
          # Upload APK to Appetize.io
          RESPONSE=$(curl -X POST "https://api.appetize.io/v1/apps" \
            -F "file=@$APK_PATH" \
            -F "platform=android" \
            -H "Authorization: Bearer $APPETIZE_API_TOKEN")
          
          # Extract and print the public URL
          PUBLIC_URL=$(echo $RESPONSE | jq -r '.publicUrl')
          echo "App deployed to Appetize.io. Public URL: $PUBLIC_URL"